DROP TABLE IF EXISTS measurement;
DROP TABLE IF EXISTS sensor;
CREATE TABLE sensor(
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name varchar(100) NOT NULL
);

CREATE TABLE measurement(
                     id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     value double precision not null,
                     raining bool,
                     created_at timestamp not null,
                     sensor_id integer REFERENCES sensor ON DELETE SET NULL
);


INSERT INTO sensor(name) VALUES ('Metran');
INSERT INTO sensor(name) VALUES ('Elster');
INSERT INTO sensor(name) VALUES ('Овен');
INSERT INTO measurement(value, raining, created_at, sensor_id) VALUES (18.9, true, '2023-05-10 23:12:24.609670', 1);
